# Generated by Django 3.2.6 on 2021-11-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_auto_20211123_1714'),
    ]

    operations = [
        migrations.DeleteModel(
            name='info',
        ),
    ]
