# Generated by Django 3.2.6 on 2021-11-30 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_post', models.CharField(max_length=30)),
                ('text_post', models.CharField(max_length=255)),
                ('date_public', models.CharField(max_length=15)),
                ('user_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
