# Generated by Django 3.2.6 on 2021-11-30 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_post_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_user',
            new_name='Post',
        ),
    ]
