# Generated by Django 3.2.6 on 2021-12-04 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_rename_post_user_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=255)),
                ('id_user', models.CharField(max_length=255)),
                ('text_comm', models.CharField(max_length=255)),
                ('data_comment', models.CharField(max_length=255)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.post')),
            ],
        ),
    ]
