# Generated by Django 3.2.6 on 2021-12-04 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_comment_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment_post',
            new_name='Comment',
        ),
    ]
