# Generated by Django 3.2.6 on 2021-12-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0008_rename_comment_post_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_chek',
            field=models.CharField(default='Nonest', max_length=255),
            preserve_default=False,
        ),
    ]
