# Generated by Django 3.2.6 on 2021-12-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0009_user_email_chek'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_cod',
            field=models.CharField(default='bdyiu3h347f43yfh74rnfur48jf7h83rj4h84fh4dn6473f8h7f4ud', max_length=255),
            preserve_default=False,
        ),
    ]
