# Generated by Django 3.2.6 on 2021-12-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0010_user_email_cod'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='image',
            field=models.ImageField(blank=True, default='images/profil.png', null=True, upload_to=''),
        ),
    ]
