# Generated by Django 3.2.6 on 2021-12-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0018_alter_info_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='username',
            field=models.CharField(default='Нету', max_length=30),
        ),
    ]
