# Generated by Django 3.2.6 on 2021-12-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0020_auto_20211220_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='status',
            field=models.CharField(default='No', max_length=30),
        ),
    ]
