# Generated by Django 3.2.6 on 2021-12-24 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0021_info_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='status',
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('if_friend', models.CharField(max_length=15)),
                ('status', models.CharField(default='No', max_length=30)),
                ('data_application', models.CharField(max_length=15)),
                ('date_acceptance_application', models.CharField(max_length=15)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
